info:
  component: server-config
  
server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gerardoharias/trackapp-config
          
profiles:
  active: dev